object Libs {
    object Versions {
        const val okHttp = "4.2.1"
        const val threeTenAbp = "1.2.1"
        const val timber = "4.7.1"
        const val stetho = "1.5.1"
        const val retrofit = "2.6.2"
        const val moshi = "1.9.1"
        const val koin = "2.0.1"
        const val navigation = "2.1.0"
        const val coreKtx = "1.1.0"
        const val viewPager2 = "1.0.0-rc01"
        const val materialComponents = "1.1.0-beta01"
        const val glide = "4.10.0"
        const val epoxy = "3.8.0"
        const val butterKnifePlugin = "10.1.0"
        const val lifecycle = "2.1.0"
        const val paging = "2.1.0"
        const val browser = "1.0.0"
        const val customTabHelper = "0.1.0-alpha1"
        const val room = "2.2.1"
        const val paris = "1.3.0"

    }

    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    const val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTenAbp}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val stetho = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    const val koinAndroid = "org.koin:koin-android:${Versions.koin}"
    const val koinAndroidxScope = "org.koin:koin-androidx-scope:${Versions.koin}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    const val navigationFragment =
        "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val navigationGradlePlugin =
        "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigation}"
    const val androidCoreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val viewPager2 = "androidx.viewpager2:viewpager2:${Versions.viewPager2}"
    const val materialComponents =
        "com.google.android.material:material:${Versions.materialComponents}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideAnnotation = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val epoxy = "com.airbnb.android:epoxy:${Versions.epoxy}"
    const val epoxyAnnotation = "com.airbnb.android:epoxy-processor:${Versions.epoxy}"
    const val epoxyDataBinding = "com.airbnb.android:epoxy-databinding:${Versions.epoxy}"
    const val epoxyPaging = "com.airbnb.android:epoxy-paging:${Versions.epoxy}"
    const val butterKnifePlugin =
        "com.jakewharton:butterknife-gradle-plugin:${Versions.butterKnifePlugin}"
    const val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val liveData = "androidx.lifecycle:lifecycle-livedata:${Versions.lifecycle}"
    const val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    const val browser = "androidx.browser:browser:${Versions.browser}"
    const val customTabHelper =
        "com.google.androidbrowserhelper:androidbrowserhelper:${Versions.customTabHelper}"
    const val room = "androidx.room:room-runtime:${Versions.room}"
    const val roomAnnotation = "androidx.room:room-compiler:${Versions.room}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    const val paris = "com.airbnb.android:paris:${Versions.paris}"
    const val parisAnnotation = "com.airbnb.android:paris-processor:${Versions.paris}"
}