object Libs {
    object Versions {
        val okHttp = "4.2.1"
        val threeTenAbp = "1.2.0"
        val timber = "4.7.1"
        val stetho = "1.5.1"
        val retrofit = "2.6.2"
        val moshi = "1.8.0"
        val koin = "2.0.1"
        val navigation = "2.1.0"
        val coreKtx = "1.1.0"
        val viewPager2 = "1.0.0-beta04"
        val materialComponents = "1.1.0-beta01"
        val glide = "4.10.0"
    }

    val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTenAbp}"
    val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    val stetho = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    val retrofitRxJavaAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    val koinAndroid = "org.koin:koin-android:${Versions.koin}"
    val koinAndroidxScope = "org.koin:koin-androidx-scope:${Versions.koin}"
    val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    val navigationGradlePlugin = "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigation}"
    val androidCoreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    val viewPager2 = "androidx.viewpager2:viewpager2:${Versions.viewPager2}"
    val materialComponents = "com.google.android.material:material:${Versions.materialComponents}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glideAnnotation = "com.github.bumptech.glide:compiler:${Versions.glide}"
}