object Libs {
    object Versions {
        val okHttp = "4.2.1"
        val threeTenAbp = "1.2.0"
        val timber = "4.7.1"
        val stetho = "1.5.1"
        val retrofit = "2.6.2"
        val moshi = "1.9.1"
        val koin = "2.0.1"
        val navigation = "2.1.0"
        val coreKtx = "1.1.0"
        val viewPager2 = "1.0.0-rc01"
        val materialComponents = "1.1.0-beta01"
        val glide = "4.10.0"
        val epoxy = "3.8.0"
        val butterKnifePlugin = "10.1.0"
        val lifecycle = "2.1.0"
        val paging = "2.1.0"
        val browther = "1.0.0"
        val customTabHelper = "0.1.0-alpha1"
        val room = "2.2.1"
    }

    val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTenAbp}"
    val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    val stetho = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    val koinAndroid = "org.koin:koin-android:${Versions.koin}"
    val koinAndroidxScope = "org.koin:koin-androidx-scope:${Versions.koin}"
    val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    val navigationGradlePlugin =
        "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigation}"
    val androidCoreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    val viewPager2 = "androidx.viewpager2:viewpager2:${Versions.viewPager2}"
    val materialComponents = "com.google.android.material:material:${Versions.materialComponents}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glideAnnotation = "com.github.bumptech.glide:compiler:${Versions.glide}"
    val epoxy = "com.airbnb.android:epoxy:${Versions.epoxy}"
    val epoxyAnnotation = "com.airbnb.android:epoxy-processor:${Versions.epoxy}"
    val epoxyDataBinding = "com.airbnb.android:epoxy-databinding:${Versions.epoxy}"
    val epoxyPaging = "com.airbnb.android:epoxy-paging:${Versions.epoxy}"
    val butterKnifePlugin =
        "com.jakewharton:butterknife-gradle-plugin:${Versions.butterKnifePlugin}"
    val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    val liveData = "androidx.lifecycle:lifecycle-livedata:${Versions.lifecycle}"
    val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    val browser = "androidx.browser:browser:${Versions.browther}"
    val customTabHelper =
        "com.google.androidbrowserhelper:androidbrowserhelper:${Versions.customTabHelper}"
    val room = "androidx.room:room-runtime:${Versions.room}"
    val roomAnnotation = "androidx.room:room-compiler:${Versions.room}"
    val roomKtx = "androidx.room:room-ktx:${Versions.room}"
}